Repository codeuino/social-platform-donut-frontend, pull requests merged in 2020-04, with the labels that each got.

#384 integrate backend with frontend and manage state on client side
  package-lock.json
  package.json
  src/App.js
  src/actions/authAction.js
  src/actions/types.js
  src/auth/auth-service.js
  src/auth/login-form/login-form.js
  src/auth/login/login.js
  src/auth/signup-form/signup-form.js
  src/reducers/authReducer.js
  src/reducers/errorReducer.js
  src/reducers/index.js
  src/reducers/postReducer.js
  src/reducers/userReducer.js
  src/store.js
  src/user/dashboard/navigation/navigation.js
  src/user/profile/popups/logout.js
  src/utils/errorHandler.js
  src/utils/setAuthToken.js
Labels: enhancement, integration

#432 Converting Settings page to Material UI
  src/user/dashboard/navigation/navigation.js
  src/user/dashboard/settings/SettingContent.js
  src/user/dashboard/settings/layouts/RightNav.js
  src/user/dashboard/settings/styles/settings.scss
Labels: enhancement, material-ui

#436 Added the updated fields in the signup page using Material-UI
  package.json
  src/actions/authAction.js
  src/auth/signup-form/signup-form.js
  src/auth/signup-form/signup-form.scss
Labels: BACKEND_INTEGRATION

#435 Added UI for forgot password
  src/auth/login-form/login-form.js
  src/auth/login-form/login-form.scss
  src/common/Popups.js
Labels: enhancement, feature

#400 Added pop-up for comment
  src/jsonData/comments.js
  src/user/dashboard/news-feed/news-feed.js
  src/user/dashboard/news-feed/popups/comment.js
  src/user/dashboard/news-feed/popups/comment.scss
Labels: enhancement, feature

#368 Improved Profile Popups to Material UI
  src/user/dashboard/navigation/navigation.js
  src/user/profile/popups/edit-profile.js
  src/user/profile/popups/followers.js
  src/user/profile/popups/logout.js
  src/user/profile/popups/popups.scss
  src/user/profile/user-info/user-info.js
Labels: material-ui

#369 Improved Navigation to MaterialUI
  src/user/dashboard/navigation/navigation.js
Labels: material-ui

#442 integrated functionality of forgot password and fixed bugs (redux devtool)
  package-lock.json
  src/actions/authAction.js
  src/actions/types.js
  src/auth/login-form/login-form.js
  src/common/Popups.js
  src/reducers/errorReducer.js
  src/reducers/index.js
  src/reducers/requestStatus.js
  src/store.js
  src/utils/setRequestStatus.js
Labels: BACKEND_INTEGRATION

#417 Added the UI for the Organisation Tab
  package-lock.json
  src/jsonData/orginfo.js
  src/user/dashboard/updates/updates.scss
  src/user/organization/org-contact/OrgContact.js
  src/user/organization/org-contact/org-contact.scss
  src/user/organization/org-info/org-info.js
  src/user/organization/org-info/org-info.scss
  src/user/organization/organization.js
  src/user/organization/organization.scss
  src/user/pinned-posts/pinned-posts.js
  src/user/pinned-posts/pinned-posts.scss
Labels: enhancement
